apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image: harshita7004/myapp:7cd4b01f1881ba5e80b94971024c7f8973440585



  template:
    metadata:
      labels:
        app: image: harshita7004/myapp:7cd4b01f1881ba5e80b94971024c7f8973440585


    spec:
      containers:
      - name: image: harshita7004/myapp:7cd4b01f1881ba5e80b94971024c7f8973440585


        image: yourdockerhubusername/myapp:latest
        ports:
        - containerPort: 3000
