apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image: harshita7004/myapp:latest

  template:
    metadata:
      labels:
        app: image: harshita7004/myapp:latest


    spec:
      containers:
      - name: image: harshita7004/myapp:latest

        image: yourdockerhubusername/myapp:latest
        ports:
        - containerPort: 3000
